title: "Nick Rogers"
description: "Personal Blog and Projects"
theme: minima
baseurl: ""
url: "https://nickrogers.dev"

# Custom CSS
css: "assets/css/style.css"

# Navigation links
links:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about/"
  - title: "Blog"
    url: "/"
  - title: "Projects"
    url: "/projects/"
